version: '3.7'

services:
    # ==========================================================================
    # MySQL
    # ==========================================================================
    mysql:
        image: ${COMPOSE_PROJECT_NAME}_mysql:${SERVICE_VERSION}
        container_name: mysql
        build:
            context: ./docker/mysql
            labels:
                - project=${COMPOSE_PROJECT_NAME}
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${HOST_DB_PORT}:3306
        volumes:
            - ./db/:/var/lib/mysql/
    # ==========================================================================
    # Nginx
    # ==========================================================================
    nginx:
        image: ${COMPOSE_PROJECT_NAME}_nginx:${SERVICE_VERSION}
        container_name: nginx
        build:
            context: ./docker/nginx
            labels:
                - project=${COMPOSE_PROJECT_NAME}
            args:
                - USER_NAME=${USER_NAME}
                - USER_UID=${USER_UID}
        ports:
            - ${HOST_HTTP_PORT}:80
        depends_on:
            - php
        volumes:
            # config
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            # www data
            - ./www:/var/www/html
        environment:
            - USER_NAME=${USER_NAME}
            - USER_UID=${USER_UID}
    # ==========================================================================
    # PHP
    # ==========================================================================
    php:
        image: ${COMPOSE_PROJECT_NAME}_php:${SERVICE_VERSION}
        container_name: php
        build:
            context: ./docker/php
            labels:
                - project=${COMPOSE_PROJECT_NAME}
            args:
                - USER_NAME=${USER_NAME}
                - USER_UID=${USER_UID}
        depends_on:
            - mysql
        volumes:
            - ./www:/var/www/html
        environment:
            - USER_NAME=${USER_NAME}
            - USER_UID=${USER_UID}
    # ==========================================================================
    # PHPMyAdmin
    # ==========================================================================
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    # ==========================================================================
    # mailCatcher
    # ==========================================================================
    mailcatcher:
        container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
        image: schickling/mailcatcher
        depends_on:
            - nginx
            - php
            - mysql
        ports:
            - 1080:1080
            - 1025:1025